// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RubroX.Infrastructure.Persistence;

#nullable disable

namespace RubroX.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RubroXDbContext))]
    partial class RubroXDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("presupuesto")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RubroX.Domain.Aggregates.Flujos.FlujoAprobacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTimeOffset>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("IniciadorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("iniciador_id");

                    b.Property<Guid?>("MovimientoId")
                        .HasColumnType("uuid")
                        .HasColumnName("movimiento_id");

                    b.Property<int>("PasoActual")
                        .HasColumnType("integer")
                        .HasColumnName("paso_actual");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid?>("RubroId")
                        .HasColumnType("uuid")
                        .HasColumnName("rubro_id");

                    b.Property<string>("TipoFlujo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_flujo");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("idx_flujos_estado");

                    b.HasIndex("RubroId")
                        .HasDatabaseName("idx_flujos_rubro");

                    b.ToTable("flujos_aprobacion", "presupuesto");
                });

            modelBuilder.Entity("RubroX.Domain.Aggregates.Flujos.PasoAprobacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AprobadorId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aprobador_id");

                    b.Property<string>("Comentario")
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset?>("FechaAccion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_accion");

                    b.Property<Guid>("FlujoId")
                        .HasColumnType("uuid")
                        .HasColumnName("flujo_id");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("RolRequerido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rol_requerido");

                    b.HasKey("Id");

                    b.HasIndex("FlujoId", "Orden")
                        .IsUnique()
                        .HasDatabaseName("uq_flujo_orden");

                    b.ToTable("pasos_aprobacion", "presupuesto");
                });

            modelBuilder.Entity("RubroX.Domain.Aggregates.Movimientos.MovimientoPresupuestal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("concepto");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<DateTimeOffset?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto");

                    b.Property<string>("Numeracion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numeracion");

                    b.Property<string>("Observacion")
                        .HasColumnType("text")
                        .HasColumnName("observacion");

                    b.Property<Guid?>("PadreId")
                        .HasColumnType("uuid")
                        .HasColumnName("movimiento_padre_id");

                    b.Property<Guid>("RubroId")
                        .HasColumnType("uuid")
                        .HasColumnName("rubro_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("idx_movimientos_estado");

                    b.HasIndex("Numeracion")
                        .IsUnique()
                        .HasDatabaseName("uq_movimiento_numeracion");

                    b.HasIndex("RubroId")
                        .HasDatabaseName("idx_movimientos_rubro");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("idx_movimientos_tipo");

                    b.ToTable("movimientos", "presupuesto");
                });

            modelBuilder.Entity("RubroX.Domain.Aggregates.Rubros.Rubro", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("AnoFiscal")
                        .HasColumnType("integer")
                        .HasColumnName("ano_fiscal");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("fuente");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<Guid?>("PadreId")
                        .HasColumnType("uuid")
                        .HasColumnName("padre_id");

                    b.Property<decimal>("SaldoComprometido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo_comprometido");

                    b.Property<decimal>("SaldoEjecutado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo_ejecutado");

                    b.Property<decimal>("SaldoInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo_inicial");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("AnoFiscal")
                        .HasDatabaseName("idx_rubros_ano_fiscal");

                    b.HasIndex("Estado")
                        .HasDatabaseName("idx_rubros_estado");

                    b.HasIndex("PadreId");

                    b.HasIndex("Codigo", "AnoFiscal")
                        .IsUnique()
                        .HasDatabaseName("uq_rubro_codigo_ano");

                    b.ToTable("rubros", "presupuesto");
                });

            modelBuilder.Entity("RubroX.Domain.Aggregates.Flujos.PasoAprobacion", b =>
                {
                    b.HasOne("RubroX.Domain.Aggregates.Flujos.FlujoAprobacion", null)
                        .WithMany("Pasos")
                        .HasForeignKey("FlujoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RubroX.Domain.Aggregates.Rubros.Rubro", b =>
                {
                    b.HasOne("RubroX.Domain.Aggregates.Rubros.Rubro", null)
                        .WithMany()
                        .HasForeignKey("PadreId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RubroX.Domain.Aggregates.Flujos.FlujoAprobacion", b =>
                {
                    b.Navigation("Pasos");
                });
#pragma warning restore 612, 618
        }
    }
}
